version: '3.4'
x-app-base: &app-base
  image: reachsh/reach-app-tut-8:latest
services:
  devnet-cfx:
    image: reachsh/devnet-cfx:0.1
  ethereum-devnet:
    image: reachsh/ethereum-devnet:0.1
  algorand-devnet:
    image: reachsh/algorand-devnet:0.1
    depends_on:
      - algorand-postgres-db
    environment:
      - REACH_DEBUG
      - POSTGRES_HOST=algorand-postgres-db
      - POSTGRES_USER=algogrand
      - POSTGRES_PASSWORD=indexer
      - POSTGRES_DB=pgdb
    ports:
      - 9392
  algorand-postgres-db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=algogrand
      - POSTGRES_PASSWORD=indexer
      - POSTGRES_DB=pgdb
  reach-app-tut-8-ETH-live:
    <<: *app-base
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=ETH-live
      - ETH_NODE_URI
      - ETH_NODE_NETWORK
  reach-app-tut-8-ETH-test-dockerized-geth: &default-app
    <<: *app-base
    depends_on:
      - ethereum-devnet
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=ETH-test-dockerized-geth
      - ETH_NODE_URI=http://ethereum-devnet:8545
  reach-app-tut-8-ALGO-live:
    <<: *app-base
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=ALGO-live
      - ALGO_TOKEN
      - ALGO_SERVER
      - ALGO_PORT
      - ALGO_INDEXER_TOKEN
      - ALGO_INDEXER_SERVER
      - ALGO_INDEXER_PORT
      - ALGO_FAUCET_PASSPHRASE
  reach-app-tut-8-ALGO-test-dockerized-algod:
    <<: *app-base
    depends_on:
      - algorand-devnet
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=ALGO-test-dockerized-algod
      - ALGO_SERVER=http://algorand-devnet
      - ALGO_PORT=4180
      - ALGO_INDEXER_SERVER=http://algorand-devnet
      - ALGO_INDEXER_PORT=8980
  reach-app-tut-8-CFX-devnet:
    <<: *app-base
    depends_on:
      - devnet-cfx
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=CFX-devnet
      - CFX_DEBUG
      - CFX_NODE_URI=http://devnet-cfx:12537
      - CFX_NETWORK_ID=999
  reach-app-tut-8-CFX-live:
    <<: *app-base
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=CFX-live
      - CFX_DEBUG
      - CFX_NODE_URI
      - CFX_NETWORK_ID
  reach-app-tut-8-: *default-app
  reach-app-tut-8: *default-app
  # After this is new!
  player: &player
    <<: *default-app
    stdin_open: true
  alice: *player
  bob: *player
