version: '3'
services:
  algorand-postgres-db:
    image: postgres:11
    environment:
      - POSTGRES_USER=algogrand
      - POSTGRES_PASSWORD=indexer
      - POSTGRES_DB=pgdb

  algorand-devnet:
    image: reachsh/algorand-devnet:0.1
    depends_on:
      - algorand-postgres-db
    environment:
      - REACH_DEBUG
      - POSTGRES_HOST=algorand-postgres-db
      - POSTGRES_USER=algogrand
      - POSTGRES_PASSWORD=indexer
      - POSTGRES_DB=pgdb
    ports:
      - 9392

  test-stdlib-ETH:
    image: reachsh/stdlib:latest
    build: .
    entrypoint: npm run test-stdlib-ETH
    environment:
      - REACH_CONNECTOR_MODE=ETH-test-embedded-ganache

  test-stdlib-ALGO:
    image: reachsh/stdlib:latest
    build: .
    entrypoint: npm run test-stdlib-ALGO
    depends_on:
      - algorand-devnet
    environment:
      - REACH_CONNECTOR_MODE=ALGO-test-dockerized-algod
      - ALGO_SERVER=http://algorand-devnet
      - ALGO_PORT=4180
      - ALGO_INDEXER_SERVER=http://algorand-devnet
      - ALGO_INDEXER_PORT=8980

  test-stdlib-FAKE:
    image: reachsh/stdlib:latest
    build: .
    entrypoint: npm run test-stdlib-FAKE
    environment:
      - REACH_CONNECTOR_MODE=FAKE-test-embedded-mock

  test-rpc-server-ETH:
    image: reachsh/stdlib:latest
    build: .
    entrypoint: npm run test-rpc-server-ETH
    environment:
      - REACH_CONNECTOR_MODE=ETH-test-embedded-ganache

  test-rpc-server-ALGO:
    image: reachsh/stdlib:latest
    build: .
    entrypoint: npm run test-rpc-server-ALGO
    depends_on:
      - algorand-devnet
    environment:
      - REACH_CONNECTOR_MODE=ALGO-test-dockerized-algod
      - ALGO_SERVER=http://algorand-devnet
      - ALGO_PORT=4180
      - ALGO_INDEXER_SERVER=http://algorand-devnet
      - ALGO_INDEXER_PORT=8980

  test-rpc-server-FAKE:
    image: reachsh/stdlib:latest
    build: .
    entrypoint: npm run test-rpc-server-FAKE
    environment:
      - REACH_CONNECTOR_MODE=FAKE-test-embedded-mock
