include $(ROOT)/VERSION
include $(ROOT)/DEPS

.PHONY: install-mo
install-mo:
	curl -sSL $(MO_URL) -o mo
	chmod +x mo
	mv mo /usr/local/bin

package.json: package.mo.json $(ROOT)/VERSION
	REACH_VERSION=$(VERSION) mo $< > $@

ts/version.ts: ts/version.mo.ts $(ROOT)/VERSION
	REACH_VERSION=$(VERSION) mo $< > $@

ts/stdlib_sol.ts: stdlib_sol.json
	(echo "export default" ; cat $<) > $@


