include $(ROOT)/VERSION
include $(ROOT)/DEPS

package.json: package.mo.json $(ROOT)/VERSION
	REACH_VERSION=$(VERSION) $(ROOT)/scripts/mo $< > $@

ts/version.ts: ts/version.mo.ts $(ROOT)/VERSION
	REACH_VERSION=$(VERSION) $(ROOT)/scripts/mo $< > $@

ts/stdlib_sol.ts: stdlib_sol.json
	(echo "export default" ; cat $<) > $@
