version: '3.4'
x-app-base: &app-base
  image: reachsh/reach-app-remote:latest
services:
  devnet-cfx:
    image: reachsh/devnet-cfx:0.1
  devnet-eth:
    image: reachsh/devnet-eth:0.1
  reach-app-remote-ETH-live:
    <<: *app-base
    environment:
      - REACH_ISOLATED_NETWORK
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=ETH-live
      - ETH_NODE_URI
      - ETH_NODE_NETWORK
  reach-app-remote-ETH-devnet: &default-app
    <<: *app-base
    depends_on:
      - devnet-eth
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=ETH-devnet
      - ETH_NODE_URI=http://devnet-eth:8545
  reach-app-remote-ALGO-devnet: *default-app
  reach-app-remote-CFX-devnet:
    <<: *app-base
    depends_on:
      - devnet-cfx
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=CFX-devnet
      - CFX_DEBUG
      - CFX_NODE_URI=http://devnet-cfx:12537
      - CFX_NETWORK_ID=999
  reach-app-remote-CFX-live:
    <<: *app-base
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=CFX-live
      - CFX_DEBUG
      - CFX_NODE_URI
      - CFX_NETWORK_ID
  reach-app-remote-: *default-app
  reach-app-remote: *default-app
