#!/bin/sh

HERE=$(dirname $(realpath $0))
HS=${HERE}/hs

if [ -z "${REACH_DOCKER}" ] && [ -d ${HS}/.stack-work ] ; then
    export STACK_YAML=${HS}/stack.yaml
    MAYBE_FAST="--fast"
    if [ "x${REACHC_RELEASE}" == "xY" ] ; then
       MAYBE_FAST=""
    fi
    stack build ${MAYBE_FAST} && \
        exec stack exec -- reachc $*
else
    cat<<EOF | docker-compose -f - run reach $*
version: '3'
services:
  reach:
    image: reachsh/reach:v0.1.0
    volumes:
      - $PWD:/app
EOF
fi
