#!/bin/sh

case "$1" in
  "bootstrap") echo "TODO" ;; # Document this in `optparse` as well

  *)
    s=$(docker run -it --rm reachsh/reach-cli:latest "$@")
    if [ "$(echo "$s" | head -n1 | tr -d '\r')" = 'RUNME' ]
      then echo "$s" | tr -d '\r' | sed 's/RUNME//' | /bin/sh
      else echo "$s"
    fi
    ;;
esac
