#!/bin/sh

IMG='reachsh/reach-cli:latest'
TMP=$(mktemp -d -p /tmp 'reach.XXXXXXXXXX')

export TMP

run_d () {
  docker run -t --rm \
    -e "REACH_EX=$0" \
    -e "REACH_VERSION" \
    -e "REACH_CONNECTOR_MODE" \
    -u "$(id -ru):$(id -rg)" \
    -v "$TMP:/app/tmp" \
    -v "$(pwd):/app/src" \
    "$IMG" --dir-project-host="$(pwd)" "$@"
}

run_s () {
  chmod 700 "$TMP/out.sh"
  sh -ac "$TMP/out.sh" "$0"
}

if ! (which make docker docker-compose >/dev/null 2>&1); then
  echo "Reach relies on an installation of make, docker, and docker-compose."
  exit 1
fi

if [ "$(docker image ls -q $IMG)" = '' ]; then
  if ! (docker pull "$IMG" && run_d update && run_s); then exit 1; fi
fi

run_d "$@"
case "$?" in
  42) run_s ;;
   1) exit 1 ;;
esac
