FROM ethereum/solc:0.7.0 as solc

FROM alpine:latest as dl-deps
RUN apk add wget unzip
WORKDIR /z3
ENV Z3_VER 4.8.8
RUN wget https://github.com/Z3Prover/z3/releases/download/z3-${Z3_VER}/z3-${Z3_VER}-x64-ubuntu-16.04.zip
RUN unzip z3-${Z3_VER}-x64-ubuntu-16.04.zip
RUN rm z3-${Z3_VER}-x64-ubuntu-16.04.zip
RUN ln -s /z3/z3-${Z3_VER}-x64-ubuntu-16.04/bin/z3 /z3/z3


FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
  curl \
  docker-compose \
  libgmp10 \
  libtinfo-dev \
  locales \
  python3-pip \
  software-properties-common

# doc deps
RUN add-apt-repository -y ppa:plt/racket && \
    apt-get update && \
    apt-get install -y racket && \
    raco pkg install https://github.com/jeapostrophe/scribble-minted.git && \
    pip3 install pygments-style-solarized

# solc
COPY --from=solc /usr/bin/solc /usr/bin/solc

# z3
COPY --from=dl-deps /z3 /z3
RUN ln -s /z3/z3 /usr/bin/z3

# stack
RUN curl -sSL https://get.haskellstack.org/ | sh

RUN stack --resolver lts-16.3 setup

# Thanks for the hint. Not sure why language-javascript built fine before this.
# https://github.com/tianon/docker-brew-debian/issues/45#issuecomment-325235517
RUN echo "LC_ALL=en_US.UTF-8" >> /etc/environment
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
RUN echo "LANG=en_US.UTF-8" > /etc/locale.conf
RUN locale-gen en_US.UTF-8
ENV LC_ALL en_US.UTF-8
