FROM reachsh/haskell-build-artifacts:latest as build
FROM alpine

RUN apk update && apk add libc6-compat gmp-dev
RUN ln -s /lib64/ld-linux-x86-64.so.2 /lib/ld-linux-x86-64.so.2

COPY --from=build /build/bin/reach /usr/bin/reach
COPY app/reach/embed/ /app/embed/

WORKDIR /app/src
ENTRYPOINT ["/usr/bin/reach"]

ARG REACH_GIT_HASH
ENV REACH_GIT_HASH="${REACH_GIT_HASH}"