FROM reachsh/reach:latest

RUN cp /root/.local/bin/reach /usr/bin/reach && chmod +x /usr/bin/reach
COPY app/reach/embed/ /app/embed/

WORKDIR /app/src
ENTRYPOINT ["/usr/bin/reach"]

ARG REACH_GIT_HASH
ENV REACH_GIT_HASH="${REACH_GIT_HASH}"
