FROM alpine AS build
RUN apk update
RUN apk add ncurses ncurses-dev libc6-compat zlib-dev gcc g++ git gmp-dev
RUN ln -s /lib64/ld-linux-x86-64.so.2 /lib/ld-linux-x86-64.so.2
RUN ln -s /usr/lib/libncursesw.so.6 /usr/lib/libtinfo.so.6
RUN wget -qO- https://get.haskellstack.org/ | sh

WORKDIR /build
COPY stack.yaml package.yaml stack.yaml.lock ./
RUN stack build --dependencies-only
COPY . /build/

RUN stack build 2>&1 | tee build-log.txt
RUN mv "$(stack path --local-install-root)/bin" /build/bin/
