FROM ethereum/solc:0.5.11 as solc

FROM alpine:latest as dl-deps
RUN apk add wget unzip
WORKDIR /z3
ENV Z3_VER 4.8.6
RUN wget https://github.com/Z3Prover/z3/releases/download/z3-${Z3_VER}/z3-${Z3_VER}-x64-ubuntu-16.04.zip
RUN unzip z3-${Z3_VER}-x64-ubuntu-16.04.zip
RUN rm z3-${Z3_VER}-x64-ubuntu-16.04.zip
RUN ln -s /z3/z3-${Z3_VER}-x64-ubuntu-16.04/bin/z3 /z3/z3


FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y curl libgmp10 docker-compose

# solc
COPY --from=solc /usr/bin/solc /usr/bin/solc

# z3
COPY --from=dl-deps /z3 /z3
RUN ln -s /z3/z3 /usr/bin/z3

# stack
RUN curl -sSL https://get.haskellstack.org/ | sh

RUN stack --resolver lts-16.3 setup
