FROM reachsh/haskell-build-artifacts AS build
FROM ethereum/solc:0.8.7         AS solc

FROM alpine

run apk update && apk add libgmpxx ca-certificates git z3 z3-dev

COPY --from=solc  /usr/bin/solc     /usr/bin/solc
COPY --from=build /build/bin/reachc /usr/bin/reachc

RUN chmod +x /usr/bin/solc
RUN chmod +x /usr/bin/z3

WORKDIR /app
ENTRYPOINT ["/usr/bin/reachc"]
ARG REACHC_HASH
ENV REACHC_HASH="${REACHC_HASH}"
ENV REACH_GIT_HASH="${REACHC_HASH}"
