# This config file contains default settings for Reach
# They can be overridden with environment variables
# See <link to help page TODO> for more info

# Whether to use Reach Cloud or Reach Local. Can be "Cloud" or "Local"
cloud-or-local = "Cloud"

# Which connector to use. Can be "ALGO" or "CFX" or "ETH"
connector = "ALGO"

# Remote project identifier. You probably want to set this in your project's reach.toml
#project = "asdf"

# Remote organization. You probably want to set this in your global reach.toml
#organization = "asdf"
