#!/usr/bin/env stack
{- stack script
 --compile
 --ghc-options -Wall
 --resolver    lts-17.8
 --package     dhall
 --package     directory
 --package     filepath
 -}

import Control.Monad      (filterM)
import Data.List          (sort)
import Dhall              (embed, inject)
import Dhall.Pretty       (prettyExpr)
import System.Directory   (listDirectory, doesDirectoryExist)
import System.Environment (getExecutablePath)
import System.FilePath    (takeDirectory)


render :: [FilePath] -> String
render es =
     "-- Code generated by gather-examples.  DO NOT EDIT.\n"
  <> (show . prettyExpr $ embed inject es)


main :: IO ()
main = do
  circleci <- takeDirectory <$> getExecutablePath
  examples <- listDirectory (circleci <> "/../examples")
          >>= filterM (\d -> doesDirectoryExist $ circleci <> "/../examples/" <> d)

  writeFile (circleci <> "/examples.dhall") $ render $ sort examples
