#!/bin/sh
HOW_MANY_EXAMPLES=$(find ../examples -maxdepth 1 -type d | wc -l)
EXAMPLES_PER_MACHINE=10
HOW_MANY_MACHINES=$(((HOW_MANY_EXAMPLES + (EXAMPLES_PER_MACHINE - 1)) / EXAMPLES_PER_MACHINE))

export HOW_MANY_EXAMPLES EXAMPLES_PER_MACHINE HOW_MANY_MACHINES
