#!/bin/sh
HOW_MANY_EXAMPLESP1=$(find ../examples -maxdepth 1 -type d | wc -l)
HOW_MANY_EXAMPLES=$((HOW_MANY_EXAMPLESP1 - 1))
EXAMPLES_PER_MACHINE=5
HOW_MANY_MACHINES=$(((HOW_MANY_EXAMPLES + (EXAMPLES_PER_MACHINE - 1)) / EXAMPLES_PER_MACHINE))

export HOW_MANY_MACHINES
