algorand-devnet:
  image: reachsh/algorand-devnet:${REACH_VERSION}
  depends_on:
    - algorand-postgres-db
  environment:
    - REACH_DEBUG
    - POSTGRES_HOST=algorand-postgres-db
    - POSTGRES_USER=algogrand
    - POSTGRES_PASSWORD=indexer
    - POSTGRES_DB=pgdb
  ports:
    ${PORTS}
