algorand-postgres-db:
  image: postgres:11-alpine
  container_name: algo-postgres-db-${APP_SERVICE}
  networks:
    - ${NETWORK}
  environment:
    - POSTGRES_USER=algogrand
    - POSTGRES_PASSWORD=indexer
    - POSTGRES_DB=pgdb

algorand-devnet:
  image: reachsh/algorand-devnet:${REACH_VERSION}
  container_name: algo-devnet-${APP_SERVICE}
  networks:
    - ${NETWORK}
  depends_on:
    - algorand-postgres-db
  environment:
    - REACH_DEBUG
    - POSTGRES_HOST=algorand-postgres-db
    - POSTGRES_USER=algogrand
    - POSTGRES_PASSWORD=indexer
    - POSTGRES_DB=pgdb
  ports:
    ${PORTS}
