devnet-cfx:
  image: reachsh/devnet-cfx:${REACH_VERSION}
  container_name: cfx-devnet
  networks:
    - ${NETWORK}
  ports:
    ${PORTS}
  labels:
    - "sh.reach.standalone-devnet=${STANDALONE_DEVNET}"
    - "sh.reach.dir-tmp=${DIR_TMP_HOST}"
    - "sh.reach.dir-project=${DIR_PROJECT_HOST}"
