depends_on:
  - algorand-devnet
environment:
  - REACH_DEBUG
  - REACH_CONNECTOR_MODE=ALGO-test-dockerized-algod
  - ALGO_SERVER=http://algorand-devnet
  - ALGO_PORT=4180
  - ALGO_INDEXER_SERVER=http://algorand-devnet
  - ALGO_INDEXER_PORT=8980
