devnet-algo-pg:
  image:          postgres:11-alpine
  hostname:       reach-devnet-algo-pg
  container_name: reach-devnet-algo-pg
  networks:
    - ${NETWORK}
  labels:
    ${LABELS}
  environment:
    - POSTGRES_USER=algogrand
    - POSTGRES_PASSWORD=indexer
    - POSTGRES_DB=pgdb

devnet-algo:
  image:          reachsh/devnet-algo:${REACH_VERSION}
  hostname:       reach-devnet-algo
  container_name: reach-devnet-algo
  networks:
    - ${NETWORK}
  ports:
    ${PORTS}
  labels:
    ${LABELS}
  depends_on:
    - devnet-algo-pg
  environment:
    - REACH_ALGO_DEBUG
    - POSTGRES_HOST=reach-devnet-algo-pg
    - POSTGRES_USER=algogrand
    - POSTGRES_PASSWORD=indexer
    - POSTGRES_DB=pgdb
