devnet-algo-pg:
  image: postgres:11-alpine
  container_name: devnet-algo-pg
  networks:
    - ${NETWORK}
  labels:
    - "sh.reach.standalone-devnet=${STANDALONE_DEVNET}"
    - "sh.reach.dir-tmp=${DIR_TMP_HOST}"
    - "sh.reach.dir-project=${DIR_PROJECT_HOST}"
  environment:
    - POSTGRES_USER=algogrand
    - POSTGRES_PASSWORD=indexer
    - POSTGRES_DB=pgdb

devnet-algo:
  image: reachsh/devnet-algo:${REACH_VERSION}
  container_name: devnet-algo
  networks:
    - ${NETWORK}
  ports:
    ${PORTS}
  labels:
    - "sh.reach.standalone-devnet=${STANDALONE_DEVNET}"
    - "sh.reach.dir-tmp=${DIR_TMP_HOST}"
    - "sh.reach.dir-project=${DIR_PROJECT_HOST}"
  depends_on:
    - devnet-algo-pg
  environment:
    - REACH_ALGO_DEBUG
    - POSTGRES_HOST=devnet-algo-pg
    - POSTGRES_USER=algogrand
    - POSTGRES_PASSWORD=indexer
    - POSTGRES_DB=pgdb
