devnet-cfx:
  image:          reachsh/devnet-cfx:${REACH_VERSION}
  hostname:       reach-devnet-cfx
  container_name: reach-devnet-cfx
  networks:
    - ${NETWORK}
  ports:
    ${PORTS}
  labels:
    ${LABELS}
  environment:
    - REACH_VERSION=${REACH_VERSION}
    - REACHC_ID
    - REACH_CONNECTOR_MODE=CFX-devnet
    - REACH_DISABLE_REPORTING
