environment:
  - REACH_DEBUG
  - REACH_NO_WARN
  - REACH_CONNECTOR_MODE=ALGO-live
  - REACH_ISOLATED_NETWORK
  - ALGO_TOKEN
  - ALGO_SERVER
  - ALGO_PORT
  - ALGO_INDEXER_TOKEN
  - ALGO_INDEXER_SERVER
  - ALGO_INDEXER_PORT
  - ALGO_NODE_WRITE_ONLY
  - ALGO_FAUCET_PASSPHRASE
