devnet-cfx:
  image:          reachsh/devnet-cfx:${REACH_VERSION}
  hostname:       reach-devnet-cfx
  container_name: reach-devnet-cfx
  networks:
    - ${NETWORK}
  ports:
    ${PORTS}
  labels:
    ${LABELS}
