import { CompletionItemKind } from 'vscode-languageserver';

type CompletionMap = { [key : string]: CompletionItemKind }

const ArrayMethodCompletion: CompletionMap = {
  'all': CompletionItemKind.Method,
  'and': CompletionItemKind.Method,
  'any': CompletionItemKind.Method,
  'concat': CompletionItemKind.Method,
  'count': CompletionItemKind.Method,
  'empty': CompletionItemKind.Method,
  'findIndex': CompletionItemKind.Method,
  'forEach': CompletionItemKind.Method,
	'includes': CompletionItemKind.Method,
	'indexOf': CompletionItemKind.Method,
	'iota': CompletionItemKind.Method,
  'length': CompletionItemKind.Method,
  'map': CompletionItemKind.Method,
  'max': CompletionItemKind.Method,
  'min': CompletionItemKind.Method,
  'or': CompletionItemKind.Method,
  'reduce': CompletionItemKind.Method,
  'replicate': CompletionItemKind.Method,
  'set': CompletionItemKind.Method,
  'sum': CompletionItemKind.Method,
  'zip': CompletionItemKind.Method,
};

export const addPrefix = (o: CompletionMap, s: string) =>
  Object.entries(o).reduce((acc, [k, v]) => {
    acc[s + "." + k] = v;
    return acc;
  }, {} as CompletionMap);

export const reachCompletionKind: CompletionMap = {
  'Address': CompletionItemKind.TypeParameter,
	'array': CompletionItemKind.Function,
  'Array': CompletionItemKind.TypeParameter,
  ...ArrayMethodCompletion,
  ...addPrefix(ArrayMethodCompletion, 'Array'),
  'assert': CompletionItemKind.Function,
	'assume': CompletionItemKind.Function,
	'balance': CompletionItemKind.Function,
  'Bool': CompletionItemKind.TypeParameter,
  'Bytes': CompletionItemKind.TypeParameter,
  'checkCommitment': CompletionItemKind.Function,
  'closeTo': CompletionItemKind.Function,
  'compose': CompletionItemKind.Function,
	'connectors': CompletionItemKind.Field,
  'const': CompletionItemKind.Keyword,
	'continue': CompletionItemKind.Keyword,
  'commit': CompletionItemKind.Function,
  'concat': CompletionItemKind.Function,
  'Data': CompletionItemKind.TypeParameter,
  'declassify': CompletionItemKind.Function,
  'deployMode': CompletionItemKind.Field,
  'digest': CompletionItemKind.Function,
  'Digest': CompletionItemKind.TypeParameter,
  'each': CompletionItemKind.Method,
  'Either': CompletionItemKind.TypeParameter,
  'ensure': CompletionItemKind.Function,
  'exit': CompletionItemKind.Function,
  'export': CompletionItemKind.Keyword,
  'fail': CompletionItemKind.Function,
  'forall': CompletionItemKind.Function,
  'forEach': CompletionItemKind.Function,
  'fromLeft': CompletionItemKind.Function,
  'fromRight': CompletionItemKind.Function,
  'Fun': CompletionItemKind.TypeParameter,
  'fromMaybe': CompletionItemKind.Function,
  'function': CompletionItemKind.Keyword,
  'hasRandom': CompletionItemKind.Function,
	'if': CompletionItemKind.Keyword,
  'implies': CompletionItemKind.Function,
	'import': CompletionItemKind.Keyword,
  'interact': CompletionItemKind.Struct,
  'isLeft': CompletionItemKind.Function,
  'isNone': CompletionItemKind.Function,
  'isRight': CompletionItemKind.Function,
  'isSome': CompletionItemKind.Function,
  'length': CompletionItemKind.Function,
  'makeCommitment': CompletionItemKind.Function,
  'makeEnum': CompletionItemKind.Function,
	'map': CompletionItemKind.Function,
  'Maybe': CompletionItemKind.TypeParameter,
	'Null': CompletionItemKind.TypeParameter,
  'Object': CompletionItemKind.TypeParameter,
	'Object.set': CompletionItemKind.Method,
	'only': CompletionItemKind.Method,
  'Participant.set': CompletionItemKind.Method,
	'pay': CompletionItemKind.Method,
  'possible': CompletionItemKind.Function,
  'publish': CompletionItemKind.Method,
	'Reach.App': CompletionItemKind.Function,
  'reduce': CompletionItemKind.Function,
  'require': CompletionItemKind.Function,
  'return': CompletionItemKind.Keyword,
  'set': CompletionItemKind.Function,
  'switch': CompletionItemKind.Keyword,
  'timeout': CompletionItemKind.Method,
  'transfer': CompletionItemKind.Function,
  'Tuple': CompletionItemKind.TypeParameter,
  'Tuple.length': CompletionItemKind.Method,
	'Tuple.set': CompletionItemKind.Method,
  'UInt': CompletionItemKind.TypeParameter,
  'unknowable': CompletionItemKind.Function,
  'verifyOverflow': CompletionItemKind.Field,
  'verifyPerConnector': CompletionItemKind.Field,
  'wait': CompletionItemKind.Function,
  'while': CompletionItemKind.Keyword,
  'zip': CompletionItemKind.Function,
};

export const reachKeywords = Object.keys(reachCompletionKind);
