node_type = "archive"
mode = "dev"
dev_block_interval_ms = 250
log_conf = "log.yaml"
jsonrpc_local_http_port = 12_539
public_rpc_apis = "all"
persist_tx_index = true
chain_id = 999
node_table_promotion_timeout_s = 9_600
mining_author = "0x11cf21383ca349b8969e7f2bc8acbf7867ac7ec3"
mining_key = "0x091ca0785ec2bd9a5eca245fdc83baddd570644f3e0489b41e515f0e5c33f3d9"
genesis_secrets = "./genesis_secret.txt"
persist_block_number_index = true
