node_type = "archive"
mode = "dev"
dev_block_interval_ms = 250
log_conf = "log.yaml"
jsonrpc_local_http_port = 12_539
public_rpc_apis = "all"
persist_tx_index = true
chain_id = 999
node_table_promotion_timeout_s = 9_600
mining_author = "0x1a4cc26bdb462df4252c9072584ffca8fb5131f1"
mining_key = "0xc72b8b13c6256b54ce428f6f67725d47194bc4ef97552867d037acd4fe6e86f3"
genesis_secrets = "./genesis_secret.txt"
